//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.WorkSession = new HashSet<WorkSession>();
        }
    
        public int Id { get; set; }
        public Nullable<int> CarId { get; set; }
        public Nullable<int> DeviceId { get; set; }
        public Nullable<int> BasementId { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<float> Longitude { get; set; }
        public Nullable<float> Latitude { get; set; }
        public string PhoneNumber { get; set; }
    
        public virtual Basement Basement { get; set; }
        public virtual Car Car { get; set; }
        public virtual Device Device { get; set; }
        public virtual DriverStatus DriverStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkSession> WorkSession { get; set; }
    }
}
