//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Backend.Database.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> WorkSessionId { get; set; }
        public System.DateTime StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public float StartLatitude { get; set; }
        public float StartLongitude { get; set; }
        public Nullable<float> DestinationLatitude { get; set; }
        public Nullable<float> DestinationLongitude { get; set; }
        public bool RequiresSpecialCar { get; set; }
        public string Start { get; set; }
        public string Destination { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        public virtual WorkSession WorkSession { get; set; }
    }
}
